# Generated by Django 2.0.3 on 2018-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=10)),
                ('target', models.CharField(default='', max_length=10)),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
    ]
